### ISSUE TITLE
How to use.

### ISSUE THREAD

**Issue by MAS150MD200** [tykeal/puppet-sslmgmt#12]
Could you please add an example how to use this puppet module?

**Comment by tykeal** [comment]
There's already some examples in the README. They're very generic, but I can definitely state that the form of the examples is exactly how this module is used in our production environment. See the USAGE section.

This module does require that you're using hiera as it has several explicit hiera calls. Issue #5 is about removing those, but at present it's a requirement.

**Comment by MAS150MD200** [comment]
Can I describe my diffucuties in email or in chat. I would be very appreciate for your help.

**Comment by tykeal** [comment]
What's the problem that you're running into?

**Comment by MAS150MD200** [comment]
Hello, I've already found solution. Your module works perfect. Thanks!
On Sep 27, 2016 03:41, Andrew Grimberg notifications@github.com wrote:What's the problem that you're running into?
